name: SateJewels
version: '2.0.7'
main: org.satellite.progiple.satejewels.SateJewels
api-version: '1.16'
depend:
  - LunaSpring
softdepend:
  - PlaceholderAPI
commands:
  satejewels:
    aliases:
      - j
      - jewels
      - sjewels
      - sj
      - satej
permissions:
  satejewels.admin:
    default: op
  satejewels.balance.another:
    default: op
  satejewels.balance:
    default: true
  satejewels.pay:
    default: op